spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customer # (1)
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate # (2)
  thymeleaf.cache: false
security.basic.enabled: false

mybatis:
  config: # mybatis config file
  mapper-locations: {} # mappers file
  check-config-location: true  # check the mybatis configuration exists
  typeHandlersPackage: # handler's package
  typeAliasesPackage:  # domain object's package 
  executorType: SIMPLE # mode of execution. Default is SIMPLE
