spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customer # (1)
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate # (2)
  thymeleaf.cache: false
security.basic.enabled: false

# mybatis config file
mybatis.config= 
# mappers file
mybatis.mapperLocations= 
# domain object's package 
mybatis.typeAliasesPackage= 
# handler's package
mybatis.typeHandlersPackage= 
# check the mybatis configuration exists
mybatis.check-config-location= true
# mode of execution. Default is SIMPLE
mybatis.executorType= SIMPLE 

